### ISSUE TITLE
bug: " ‘camera_trackball’ was not declared " error on rendering/glwidget.cpp

### ISSUE THREAD

**Issue by mseefelder** [LCG-UFRJ/tucano#1]
On "utils/qttrackballwidget.hpp", "camera_trackball" was substituted by "camera".

**Comment by marroquim** [comment]
corrected. All samples are compiling correctly now.

**Comment by thiagowfx** [comment]
Fixed on 59b917e32a7d6c008a8d46d06b0842a32df3a808.
